### ISSUE TITLE
BettIR Mod

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-Community#18]
Saw this mod on the workshop, haven't tested it or anything but what is people's opinions on it?

https://steamcommunity.com/sharedfiles/filedetails/?id=2260572637

**Comment by SM-BJS** [comment]
It's compatible with RHS's NVGs as well.

**Comment by markusa380** [comment]
I would be very careful with a mod like this. Here's why.

Although most of the guys reading this will know most of what I'm explaining already, but I will start at the beginning so we can all be on the same page.

There's two forms of night vision.
**Active** night vision is a better word for using IR illuminators and either digital or analogue image sensors that can pick up light in the infrared spectrum. It has origins during the early cold war where these optical devices where rare and a strong advantage in any circumstance. Today it's mainly used in asymmetric warfare where one side doesn't have access to anything more than an AK.
**Passive** night vision is much more modern and has only started to become viable in combat since around 2000. The optical sensors are always analogous and intensify low amounts of light to such an extent that apparently dark environments can be navigated and ultimately fought in.

This mod is a way to bring active night vision into ACE night vision.

I would strongly oppose that. Human intuition tells us that when using a flashlight, not only can we see what otherwise would lie in the dark, also anyone can see us.
With active night vision it's the same principle, but slightly more complicated. If someone else uses night vision as well, they will perceive the user as what can be only called a walking lighthouse. This wouldn't be much of an issue if it wasn't for the problem of unexperienced users of active night vision to feel secure in the dark (as they perceive the darkness outside of the eyepiece as well, represented as the black border on screen) while they actually are highly visible to anyone with even low tech night vision or even just cameras (although I don't think that's simulated).

In our group, active night vision would lead to a lot of frustration when used against anyone except militias.

Of course, I don't want to just criticise - I think we should use other means of illumination instead, namely flares for outdoors and regular weapon mounted flashlights indoors.

**Comment by SM-BJS** [comment]
Hi Markus, these are very valid points.

In terms of the ACE Settings, yea I think I will go through and alter them a little bit further as they do seem to be a little off occasionally.

In regards to avoiding overcast at night, we tend to do it to mix things up. In all missions I'd pick to wait for the perfect weather but after a while it gets a tad boring so we use the weather to our advantage to keep everyone's attention in a night time operation for example.

Hopefully people reading this and will start to take flashlights on their weapons. I know that most Apollo members take a laser/flashlight attachment already.

I'll leave this issue open for a little while longer in case others want to give their input, but as it stands, we'll scrap this suggestion.

**Comment by markusa380** [comment]
Sounds good.

ACE night vision tries to be as realistic as possible under the limitations of Arma.

One of the effects of this is that light scattering isn't simulated, which makes almost all environments too dark in all circumstances. Street lamps, vehicles, flashlights and even the distant scatter of an airfield should make it very easy to see with night vision in many circumstances, on the other hand forests should be dark even then.

Another problem is mono- vs binoculars. The human brain is incredibly good at recognizing even the faintest of shapes through binocular NVDs as it can "filter" out the noise between the two tubes. ACE on the other hand treats mono- and binoculars the same, making binoculars much less efficient than in reality, especially in very low light conditions. On the other hand the field of view between PVS-14 and PVS-15 should be the same circle, and not like the binocular devices in Arma with that 8 shape.

**Comment by SM-BJS** [comment]
This mod will not added.
