### ISSUE TITLE
ACE night vision parameter tuning

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#19]
As a follow-up of the ticket for BettIR, I thought it would make sense to create a separate ticket to discuss possible modifications to ACE settings to make night vision more realistic and enjoyable.

Things to consider:
- Less noise and later cutoff in very dark conditions for binocular devices to simulate the human eyes & brain
- More environmental light to work around missing light scattering
- Less infrared fog

**Comment by SM-BJS** [comment]
I have reduced the noise and the infared fog./

Environment light would be up to the map/location/mission makers.

We will test the new settings for a week or two.

**Comment by SM-BJS** [comment]
After the tests last night, it turns out that even by bringing all of the NVG settings down to minimals, it still doesn't aid that well and that the weather and season is the largest factor. 

The mission makers will change the weather and season in night operations to make it easier for us to see. I will also edit the NVG settings live during operations incase it is too bright/too op.
