### ISSUE TITLE
Not issue, just a request

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#76]
In regards to our corpses in cases of casualties/respawning, we could apply a penalty clause or a reward system to retrieving dead bodies from the AO, for example a person dies, his body can be placed in a body-bag and brought back to the HQ for either avoiding penalty or being rewarded. It feels right for cases of mas-cas where the amount of casualties would hinder the combat effectiveness of a unit, like a ticket system where a squad such as Ares can have a pool of 2 tickets, tickets being re-reimbursed with the retrieval of bodies kinda like battlefield.

**Comment by SM-BJS** [comment]
This is an interesting idea. It has quite a few negatives but I'll forward the idea to unit leadership to get further opinion.

**Comment by SM-BJS** [comment]
Leadership have concluded that this idea will not be implemented due to multiple negative impacts such as having to do a 'clean up' of dead bodies after each operation as well as issues that occur due to the Arma physics that are used on the body bags.

It was stated that it's a good idea from a realism/immersion standpoint but unfortunately it would not work well within Arma and with the logistics that we already have in place. Thanks for the suggestion though.
