### ISSUE TITLE
Blacklisting items that don't work

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#99]
As a result of the 100th time arguing with the use of smokes and their usefulness, there is apparently only 1 smoke grenade that does conceal against AI, with the rest being no more than decorative, also one of the m84 stun grenades and similar cause damage to civilians, so we aren't supposed to use them, so maybe blacklist them to avoid confusing them as there are lots of grenades...

**Comment by SM-BJS** [comment]
Do you have a list of the grenades and what is broken about them?

**Comment by wearhint** [comment]
I will make some tests and ask folks who already did their tests and let you know the specific grenades, the broken thing is in reference to smoke grenades not offering concealment from AI and the stun grenades that cause damage to civilians like the zarya grenade or the blue stun grenade. The reasoning is that there so many grenades in the arsenal that it gets confusing to keep a mental image of what we are supposed to use and what should be used and what is just not functional so just a general cleaning up via blacklisting would be appreciated

**Comment by wearhint** [comment]
testing all smoke grenades proved that despite throwing multiple nades, effective smoke spread was achieved but no concealment was given to the units, headshots and precise shooting proved that AI can see through the biggest and densest smoke screens, affecting all smoke grenades, so no point blacklisting all the smokes when none of them work.
Frag grenades all proved adequate, however the impact grenades don't in fact detonate on impact which has the bad habit of bouncing off the target but the biggest issue were the anti-tank grenades that detonate in your hand instead of on target and even if they leave the hand, they go like 10cm and detonate...
Stun grenades were an abysmal failure. All stun, concussion and flash nades proved outright fatal except for 2: the white stripe m84 and the 9-bang stuns were the only ones to only inflict pain without injuries. next message will be the suggested blacklist items to reduce confusing them from ones that work.

**Comment by wearhint** [comment]
Ei. Hgr. 39 Concussive (Early) - WAS LETHAL
Ei. Hgr. 39 Concussive (Late) - WAS LETHAL
Mk 3A1 Concussion - literally caused more death than the actual frag nades
Mk3A2 Concussion grenade - killed CSAT armour lvl 5 and EOD specialists
M7A3 CS Gas Grenade - although it makes civis make an animation and helping arrest them, it does cause death to whoever is standing near it...
M84 stun grenade with blue stripe - caused large and high velocity wounds.
RshB P98 caused serious injury with minimal stun effect.
Plamya-M - detonated harder than the hirosima bomb and killed everything.
Zarya-2 - did not kill anyone but did cause serious wounds and fatal blood loss on everyone in visual range.
RKG-3EM - anti tank grenade that kills the thrower rather than a tank even if its 15cm away from the thrower.
BRK M79 - same as above, no difference.
Fakel - caused serious wounds to civis with almost zero stun effect.
Fakel-S - same as above but in blue.

**Comment by SM-BJS** [comment]
Sweet, thanks for the detailed analysis, I’ll look into it once I’ve fully recovered.

**Comment by wearhint** [comment]
No worries, its not urgent or anything, recovery is your priority man, get well soon!

**Comment by SM-BJS** [comment]
_Disclaimer: I tested all of the below in the Editor, in the Ace Arsenal simulator and on our server on the training map, with both armed & armoured AI as well as completely unarmoured civilian AI._

After doing a bit of research, the Ei. Hgr. 39 Concussive grenades are in fact grenades and not flash bangs. The "Concussive" refers to the concussive blast that the grenade caused to shock and disorient nearby enemy. Nonetheless, it is a WW2 German grenade that we would never have any need for and to remove any confusion I have blacklisted them. 

Similarly with the Mk3A2, they are "Concussive" grenades which are more powerful than fragmentation grenades as their role is to send a shock wave rather than to spread shrapnel on explosion (and were actually used for demolition in some cases) so the damage dealt makes sense. These grenades in particular were designed to produce casualties during close combat with the intention of minimizing danger to friendly personnel (so were like a BTEC grenade), but again we'd never have a use for these and to prohibit confusion I've blacklisted these as well (p.s. the A1 variant isn't in our modset).

I agree with the M7A3, it deals a stupid amount of damage considering it's role so I've blacklisted that.

I tested the M84 stun grenade with the blue stripe multiple times and I could only ever get a maximum of one minor bruise on the torso even when it was thrown directly at an individual or a group of people completely unarmed (simulating civilians) and the AI reacted to it correctly. I also tested out the other M84s just to be sure and the Ace version (the white stripe one) did no damage at all and the BR M84 is a Frag Grenade so that's expected, so I have left this stun grenade as is.

Similarly with the RshB P98, the stun effect works exactly as intended and the damage was 1-3 bruises most of the time but with an added 1/8 chance of 1x large avulsion. To avoid confusion between what to use as well as the fact that the M84 offers a much lower injury rate, I have blacklisted this.

Regarding the Plamya-M, that was pretty funny to watch an almost atomic mushroom cloud rise from the explosion, but damage was similar to the M84 with only ever bruises and the stun effect worked as intended, so I will leave this in.

The Zarya-2 was the exact same as the Plamya-M, just without the mushroom cloud of Hiroshima, so will be left.

The RKG-3EM & the BRK M79 are exactly like you said, they're more of a dead man's switch than an anti-tank grenade. I did have a little bit more luck using the vanilla throwing system as opposed to the ace throwing, but very rarely with any success and we use ace throwing all the time, so they have both been blacklisted.

The Fakel is a grenade, not a stun hence the explosive damage. As to why it says "Flashbang" when you select it, I believe it is a config error, but to remove confusion, I've blacklisted it. The Fakel-S is the stun variant (the S stands for stun) and through testing gave the same results as the M84 stun and so it will be left as is.

Thanks for looking into this and reporting it, would've never found the broken ones without it so cheers!

The above changes have been put in place in Framework update 1.5.5.

**Comment by wearhint** [comment]
![ArmA 3 Screenshot 2022 08 28 - 15 02 39 42](https://user-images.githubusercontent.com/86921632/187073246-0bf4a8cf-91a1-44e5-9e1a-1dde5d90557c.png)
Mk 3A1 Concussion is in the modset

**Comment by SM-BJS** [comment]
Oh there's a space between it that's why I couldn't find it, cool I'll blacklist that as well when I get around to it, cheers 👍🏼

**Comment by SM-BJS** [comment]
Included in framework update version 1.5.6
